public class TestTriggerHandler {
	/*public static void calculateTestimonyLength(List<Account> essayList) {        
        for(Account essay : essayList) {
           
            essay.Conta__c = essay.MilenaTeste__c.length();
            
            
            List<String> testimonyArr = essay.MilenaTeste__c.split(' ');
            essay.Conta__c = testimonyArr.size();            
        }       
    }  */
}